---
- name: install git
  apt: name=git state=present
  sudo: yes

- name: install binutils
  apt: name=binutils-dev state=present
  sudo: yes

- name: install mktemp
  apt: name=mktemp state=present
  sudo: yes

- name: install mtools
  apt: name=mtools state=present
  sudo: yes

- name: install nasm
  apt: name=nasm state=present
  sudo: yes

- name: install perl
  apt: name=perl state=present
  sudo: yes

- name: install mingw32
  apt: name=mingw32-binutils state=present
  sudo: yes

- name: install mingw-w64
  apt: name=mingw-w64 state=present
  sudo: yes

- name: install e2fslibs-dev
  apt: name=e2fslibs-dev state=present
  sudo: yes

- name: check out syslinux source repository
  git:  repo=https://git.kernel.org/pub/scm/boot/syslinux/syslinux.git
        dest="{{ syslinux_build_env_path }}/syslinux"
        force=yes accept_hostkey=yes
        version={{ gittag }}

- name: apply syslinux patch
  patch: >
        src=0001-Fix-compiling-failure-on-Ubuntu-14.04.patch
        basedir="{{ syslinux_build_env_path }}/syslinux"
        strip=1
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | int >= 14

- name: clean the build
  command: make clean
  args:
    chdir: "{{ syslinux_build_env_path }}/syslinux"

- name: build the gpxe code
  command: make
  args:
    chdir: "{{ syslinux_build_env_path }}/syslinux"

- name: fetching compiled files
  fetch: src={{ syslinux_build_env_path }}/syslinux/gpxe/src/bin/{{ item }}
         dest={{ syslinux_build_artifact_path }}/{{ item }} fail_on_missing=yes
         flat=yes
  with_items:
    - undionly.kkpxe
