language: bash
sudo: required
dist: trusty
before_script:
# Rollback to 3.13 until initrd boot issue has been resolved
- sed -i 's/3.16.0-25-generic/3.13.0-32-generic/g' group_vars/on_imagebuild
- sed -i '24,25 s/^/#/' vars/basefs.yml
- sudo apt-add-repository -y ppa:ansible/ansible
- sudo apt-get update -q
- sudo apt-get install -y -q ansible=1.5.4+dfsg-1 
- sudo modprobe overlayfs
script:
- sudo ansible-playbook -i hosts all.yml
before_deploy:
- sudo chmod 644 /tmp/on-imagebuilder/builds/*
- sudo chmod 644 /tmp/on-imagebuilder/ipxe/*
deploy: 
  provider: bintray
  file: .bintray.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
  on:
    all_branches: true

notifications:
  slack:
    rooms:
    - secure: "LL9DcQQBGZ7IhpzGHRsjFGjEjGFBCG5y4yDIWeGhKZGpFPzbHF2BJXRqdsnDiRozJ2b8BbYPDAcxwEUb6k8pN2Q8TWbGEzHApBfK/ak0T4X49mbjb3I/v218MUkMjPT5G6kTUY1t8WekQDt3Wo5IokZN1iOvy+Trz40/hsRuhN5YCH3MHUrWMCIlwJVbXD1kofw090CY9xc6XVmzgXMHXyVA+TfkOzJQ2T1DCdw4wqe5p3O9Y9/um3NGbCMbbpCTto2iMoiGOu03S+m/YDOgtT+15ieST3nhvFnuskpeWbYQ89nLqNbwjXchBr0G1Wy7l3M3eARA+drYHW7MnNwbUuTRn+EyLUu/xs32iRfMS4K77KD5zXfKnKWzpMLh3ckwpcliL7njoDoCn76p1d5GmlaBTyCWKNJudmAzgDYawmZOAfVzn/Keag5LoAdkQ9s3nVS2A1c/p1oGCWxYT69mZqigSClrlWO1uyUpReiw+2ZJNIerwn1aRQWCFcNefnTw+G81fxzRq68hJsg3MhrpQu57DIALg7ZJ95WqpfG91y0YaXgqfP3TDDtsxYSVGKcNsqTqPeNkatjaZuqqVVb/LfISIIoGV57/0CQbsA6seH8veJAtMn19kBCBJRqwPC6grMBOcd9nzZCLipW0a6cRWiomhfeLteo/vewmbo4c/kU="
    on_success: never
    on_failure: always
    on_start: never
