---
- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  pre_tasks:
    - include: ../tasks/unmount_rootfs.yml
    - include: ../tasks/mount_rootfs.yml
  roles:
    - ../../roles/initrd/make_initrd_build_env

- hosts: initrd_build_env_chroot
  vars_files:
    - ../../{{ config_file }}
  roles:
    - ../../{{ provisioner }}
    - ../../roles/initrd/build_initrd

- hosts: build_local
  vars_files:
    - ../../{{ config_file }}
  tasks:
    - include: ../tasks/unmount_rootfs.yml
