---
- name: install git
  apt: name=git state=present
  sudo: yes

- name: install liblzma-dev
  apt: name=liblzma-dev state=present
  sudo: yes

- name: install syslinx and genisoimage
  apt: name=syslinux state=present
  apt: name=genisoimage state=present
  sudo: yes

- name: install binutils
  apt: name=binutils-dev state=present
  sudo: yes

- name: install libiberty-dev
  apt: name=libiberty-dev state=present
  sudo: yes

- name: check out iPXE source repository
  git:  repo=https://git.ipxe.org/ipxe.git
        dest="{{ ansible_env.HOME }}/ipxe"
        force=yes accept_hostkey=yes
        version={{ gitbranch }}

- name: copy in general.h configuration file for build
  copy: src=general.h dest="{{ ansible_env.HOME }}/ipxe/src/config/local/general.h"
  sudo: no

- name: copy in the default.ipxe script
  copy: src=default.ipxe dest="{{ ansible_env.HOME }}/ipxe/src/default.ipxe"
  sudo: no

- name: clean the build
  command: make clean
  args:
    chdir: "{{ ansible_env.HOME }}/ipxe/src"

- name: build the general code
  command: make EMBED=default.ipxe
  args:
    chdir: "{{ ansible_env.HOME }}/ipxe/src"

- name: build the general efi 64
  command: make bin-x86_64-efi/snponly.efi EMBED=default.ipxe
  args:
    chdir: "{{ ansible_env.HOME }}/ipxe/src"

- name: build the general code efi 32
  command: make bin-i386-efi/snponly.efi
  args:
    chdir: "{{ ansible_env.HOME }}/ipxe/src"

- name: fetch the resulting files
  fetch: src={{ ansible_env.HOME }}/ipxe/src/bin/{{ item }} 
         dest={{ ipxe_build_artifact_path }}/{{ item }} fail_on_missing=yes
         flat=yes
  with_items:
    - ipxe.pxe
    - undionly.kpxe

- name: fetch the resulting files efi 64 bit file
  fetch: src={{ ansible_env.HOME }}/ipxe/src/bin-x86_64-efi/{{ item }}
        dest={{ ipxe_build_artifact_path }}/monorail-efi64-snponly.efi fail_on_missing=yes
        flat=yes
  with_items:
    - snponly.efi

- name: fetch the resulting efi 32 bit file
  fetch: src={{ ansible_env.HOME }}/ipxe/src/bin-i386-efi/{{ item }}
        dest={{ ipxe_build_artifact_path }}/monorail-efi32-snponly.efi fail_on_missing=yes
        flat=yes
  with_items:
    - snponly.efi

# - name: clean the build
#   command: make clean
#   args:
#     chdir: "{{ ansible_env.HOME }}/ipxe/src"

# - name: build the debug code
#   command: make DEBUG=pci,device,intel,undinet,undionly EMBED=default.ipxe
#   command: make DEBUG=pci,device,intel bin/intel.pxe EMBED=default.ipxe
#   args:
#     chdir: "{{ ansible_env.HOME }}/ipxe/src"
